# Generated by Django 4.2 on 2023-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(null=True)),
                ('winning_bid_max', models.FloatField()),
                ('winning_bid_min', models.FloatField()),
                ('winning_bid_mean', models.FloatField()),
                ('auction_trading_volume', models.FloatField()),
                ('auction_lots_count', models.IntegerField()),
                ('all_auctions_lots_count', models.IntegerField()),
                ('auction_name', models.CharField(max_length=200)),
                ('auction_slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
